[package]
name = "unique_id_grabber"
version = "0.1.0"
authors = ["Khionu Sybiern <dev@khionu.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.7"
structopt = "0.3.14"
